accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'
urlpatterns = [
    path('register', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('dashboard', views.dashboard, name="dashboard"),

    path('activate/<uidb64>/<token>/', views.activate, name="activate"),
    path('forgot-password', views.forgotPassword, name="forgotPassword"),
    path('reset-password-confirm/<uidb64>/<token>/', views.reset_password_confirm, name="resetPasswordConfirm"),
    path('reset-password', views.reset_password, name="resetPassword"),
]

carts/urls.py
from django.urls import path
from . import views

app_name = "carts"
urlpatterns = [
    path('', views.cart, name="cart"),
    path('add_cart/<int:product_id>', views.add_cart, name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name="remove_cart_item"),

    path('checkout/', views.checkout, name="checkout"),
]

greatKart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.

class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address')

        if not username:
            raise ValueError('User must have an username')

        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, first_name, last_name, username, email, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50)

    #required
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']
    objects = MyAccountManager()

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True
    



accounts/forms.py
from django import forms
from .models import Account

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }))
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'password']
        
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
    
    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )
        return cleaned_data

accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from .models import Account
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
# email verification
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

from carts.models import Cart, CartItem
from carts.views import _cart_id
import  requests


# Create your views here.

def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email.split("@")[0]
            user = Account.objects.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
            user.phone_number = phone_number
            user.save()


            # User email verification
            current_site = get_current_site(request)
            mail_subject = "Please activate Your account"
            message = render_to_string('accounts/account_verification_email.html', {
                'user':user,
                'domain':current_site,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':default_token_generator.make_token(user),
            })

            to_email = email
            send_mail = EmailMessage(mail_subject, message, to=[to_email])
            send_mail.content_subtype = 'html'
            send_mail.send()

            # messages.success(request, 'Congratulations! We have sent you a verification email to your email address. Please verify it.')
            new_user_isActivated = Account.objects.get(email=email).is_active

            return redirect('login/?verified='+ str(new_user_isActivated) +'&email='+ email)
    else:
        form = RegistrationForm()

    context={
        'form': form
    }
    return render(request, 'accounts/register.html', context)

def login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email, password=password)

        if user:
            try:
                cart = Cart.objects.get(cart_id = _cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)

                    # Getting product variations by cart id
                    product_variation = []
                    for item in cart_item:
                        variation = item.variations.all()
                        product_variation.append(list(variation))

                    # Get the cart items from the user to access his product variations
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variations.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                item.user = user
                                item.save()


            except:
                pass
            auth_login(request, user)
            messages.success(request, 'You are now logged in')
            url = request.META.get('HTTP_REFERER')
            try:
                query = requests.utils.urlparse(url).query
                # next=/cart/checkout/
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
            except:
                return redirect('home')
        
        else:
            messages.error(request, 'Invalid login credentials')
            return redirect('accounts:login')

    return render(request, 'accounts/login.html')

@login_required
def logout(request):
    auth_logout(request)
    return redirect('home')


def  activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congratulations! Your account is activated.')
        return redirect('accounts:login')
    else:
        messages.error(request, 'Invalid activation link')
        return redirect('accounts:register')
    

@login_required(login_url='accounts:login')
def dashboard(request):
    return render(request, 'accounts/dashboard.html')

def forgotPassword(request):
    if request.method == "POST":
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            current_site = get_current_site(request)
            mail_subject = "Reset Your Password"
            message = render_to_string('accounts/reset_password_email.html', {
                'user':user,
                'domain':current_site,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':default_token_generator.make_token(user),
            })

            to_email = email
            send_mail = EmailMessage(mail_subject, message, to=[to_email])
            send_mail.content_subtype = 'html'
            send_mail.send()

            messages.success(request, 'Password reset email has been sent to your email address.')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Account does not exist')
            return redirect('accounts:forgotPassword')
    return render(request, 'accounts/forgot_password.html')

def reset_password_confirm(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.success(request, 'Please reset your password')
        return redirect('accounts:resetPassword')
    else:
        messages.error(request, 'This link has been expired')
        return redirect('accounts:login')


def reset_password(request):
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['password2']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset successful')
            return redirect('accounts:login')
        else:
            messages.error(request, 'Password do not match')
            return redirect('accounts:resetPassword')
    else:
        return render(request, 'accounts/reset_password.html')

templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block title %}
    {{user.first_name}} {{user.last_name}}'s Dashboard
{% endblock  %}
    
{% block content %}
    <!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">

    <div class="container">
        <div class="row">
        <aside class="col-md-3">
            <!--   SIDEBAR   -->
            <ul class="list-group">
                <a class="list-group-item active" href="#"> My order history </a>
                <a class="list-group-item" href="#"> Transactions </a>
                <a class="list-group-item" href="#"> Return and refunds </a>
                <a class="list-group-item" href="#">Settings </a>
                <a class="list-group-item" href="#"> My Selling Items </a>
                <a class="list-group-item" href="#"> Received orders </a>
            </ul>
            <br>
            <a class="btn btn-light btn-block" href="{% url 'accounts:logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
            <!--   SIDEBAR .//END   -->
        </aside>
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Order ID: 6123456789</strong>
                <span>Order Date: 16 December 2018</span>
            </header>
            <div class="card-body">
                <div class="row"> 
                    <div class="col-md-8">
                        <h6 class="text-muted">Delivery to</h6>
                        <p>Michael Jackson <br>  
                        Phone +1234567890 Email: myname@pixsellz.com <br>
                        Location: Home number, Building name, Street 123,  Tashkent, UZB <br> 
                        P.O. Box: 100123
                         </p>
                    </div>
                    <div class="col-md-4">
                        <h6 class="text-muted">Payment</h6>
                        <span class="text-success">
                            <i class="fab fa-lg fa-cc-visa"></i>
                            Visa  **** 4216  
                        </span>
                        <p>Subtotal: $356 <br>
                         Shipping fee:  $56 <br> 
                         <span class="b">Total:  $456 </span>
                        </p>
                    </div>
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
            <div class="table-responsive">
            <table class="table table-hover">
                <tr>
                    <td width="65">
                        <img src="../images/items/1.jpg" class="img-xs border">
                    </td>
                    <td> 
                        <p class="title mb-0">Product name goes here </p>
                        <var class="price text-muted">USD 145</var>
                    </td>
                    <td> Seller <br> Nike clothing </td>
                    <td width="250"> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
                </tr>
                <tr>
                    <td>
                        <img src="../images/items/2.jpg" class="img-xs border">
                    </td>
                    <td> 
                        <p class="title mb-0">Another name goes here </p>
                        <var class="price text-muted">USD 15</var>
                    </td>
                    <td> Seller <br> ABC shop </td>
                    <td> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
                </tr>
                <tr>
                    <td>
                        <img src="../images/items/3.jpg" class="img-xs border">
                    </td>
                    <td> 
                        <p class="title mb-0">The name of the product  goes here </p>
                        <var class="price text-muted">USD 145</var>
                    </td>
                    <td> Seller <br> Wallmart </td>
                    <td> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
                </tr>
            </table>
            </div> <!-- table-responsive .end// -->
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock  %}
    

templates/accounts/forgot_password.html
{% extends 'base.html' %}

{% block title %}
    Forgot Password
{% endblock  %}


{% block content %}
<div class="card mx-auto" style="max-width: 600px; margin-top:100px;">
    <div class="card-body">
    <h4 class="card-title mb-4">Reset Password</h4>
    {% include 'components/alert.html' %}
    <form action="{% url 'accounts:forgotPassword' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
           <input type="email" class="form-control" placeholder="Email Address" name="email">
        </div> <!-- form-group// -->
         <!-- form-group// -->
        
        <div class="form-group">
            <P class="float-right">Remember Password? <a href="{% url 'accounts:login' %}">  Login</a> </P>
         
        </div> <!-- form-group form-check .// -->
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block"> Submit </button>
        </div> <!-- form-group// -->    
    </form>
    </div> <!-- card-body.// -->
  </div> <!-- card .// -->

   <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
   <br><br>
{% endblock  %}
    

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}
    Login Page
{% endblock %}
    

{% block content %}


{% if request.GET.verified == 'False'%}
    

    
<div class="container mx-auto alert alert-info" role="alert" style="max-width: 600px; margin-top:100px; margin-bottom:100px">
<p>We have sent You a link to [{{request.GET.email}}], click on that link to verify your account. </p>
</div>

{% else %}
<!-- ============================ COMPONENT LOGIN   ================================= -->
<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
    <div class="card-body">
    <h4 class="card-title mb-4">Sign in</h4>
    {% include 'components/alert.html' %}
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
           <input type="email" class="form-control" placeholder="Email Address" name="email">
        </div> <!-- form-group// -->
        <div class="form-group">
          <input type="password" class="form-control" placeholder="Password" name="password">
        </div> <!-- form-group// -->
        
        <div class="form-group">
            <a href="{% url 'accounts:forgotPassword' %}" class="float-right">Forgot password?</a> 
         
        </div> <!-- form-group form-check .// -->
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block"> Login  </button>
        </div> <!-- form-group// -->    
    </form>
    </div> <!-- card-body.// -->
  </div> <!-- card .// -->

   <p class="text-center mt-4">Don't have account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
   <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->
{% endif %}
{% endblock  %}
    

<!-- Hi {{user.first_name}} {{user.last_name}}, Please click below link to verify your account
    http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}-->

templates/accounts/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}Registration Page{% endblock  %}
{% block content %}
<section class="section-content padding-y">

    <!-- ============================ COMPONENT REGISTER   ================================= -->
        <div class="card mx-auto" style="max-width:520px; margin-top:40px;">
          <article class="card-body">
            <div class="div">
                {% include 'components/alert.html' %}
            </div>
            <header class="mb-4"><h4 class="card-title">Sign up</h4></header>
            <form method="POST">

                {% csrf_token %}
                    <div class="form-row">
                        <div class="col form-group">
                            <label>First name</label>
                            {{form.first_name}}
                        </div> <!-- form-group end.// -->
                        <div class="col form-group">
                            <label>Last name</label>
                            {{form.last_name}}
                        </div> <!-- form-group end.// -->
                    </div> <!-- form-row end.// -->
                    <div class="form-group">
                        <label>Email</label>
                        {{form.email}}
                        <small class="form-text text-muted">We'll never share your email with anyone else.</small>
                    </div> <!-- form-group end.// -->
                    
                    <div class="form-group">
                        <label>Phone Number</label>
                        {{form.phone_number}}
                    </div>


                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Create password</label>
                            {{form.password}}
                        </div> <!-- form-group end.// --> 
                        <div class="form-group col-md-6">
                            <label>Repeat password</label>
                        {{form.confirm_password}}
                        </div> <!-- form-group end.// -->  
                    </div>
                    <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block"> Register  </button>
                    
                    </div> <!-- form-group// -->   
                    {{form.email.errors}}
                    {{form.non_field_errors}}   
                        
                </form>
            </article><!-- card-body.// -->
        </div> <!-- card .// -->
        <p class="text-center mt-4">Have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
        <br><br>
    <!-- ============================ COMPONENT REGISTER  END.// ================================= -->
    
    
    </section>
{% endblock  %}
    

templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block title %}
    Reset Password
{% endblock  %}


{% block content %}

<div class="card mx-auto" style="max-width: 600px; margin-top:100px; margin-bottom:100px">
    <div class="card-body">
    <h4 class="card-title mb-4">Reset Password</h4>
    {% include 'components/alert.html' %}
    <form action="{% url 'accounts:resetPassword' %}" method="POST">
        {% csrf_token %}
        
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Password" name="password">
          </div>
          <div class="form-group">
            <input type="password" class="form-control" placeholder="Re-enter Password" name="password2">
          </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block"> Submit </button>
        </div> <!-- form-group// -->    
    </form>
    </div> <!-- card-body.// -->
  </div> <!-- card .// -->
{% endblock %}

templates/accounts/reset_password_email.html

{% autoescape off %}
    Click the link below to reset your password. 
    http://{{domain}}{% url 'accounts:resetPasswordConfirm' uidb64=uid token=token %} 
{% endautoescape %}